[package]
name = "irancell_pro_invite"
version = "6.0.0"
edition = "2021"

[dependencies]
# استفاده از rustls برای امنیت و سرعت بالا، و socks برای پشتیبانی پراکسی
reqwest = { version = "0.12", features = ["json", "gzip", "brotli", "deflate", "zstd", "socks", "rustls-tls", "cookies"], default-features = false }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.9.2" # آخرین نسخه رندوم
chrono = "0.4"
anyhow = "1.0"
