[package]
name = "irancell_ref"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
rand = "0.8"
chrono = "0.4"
# تغییر مهم: استفاده از نسخه شبیه‌ساز مرورگر
reqwest-impersonate = { version = "0.11", features = ["socks5", "cookies"] } 
indicatif = "0.17"  # برای رابط کاربری
once_cell = "1.18"
